// Generated by scripts/generate-provider-host-contracts.ts.
// This release-only shim is derived from host imports; do not edit by hand.

export type AuthProvider<T = any, U = any, V = any, W = any, X = any> = any;
export const AuthProvider: any = undefined;
export type CLERK_PROVIDER_ID<T = any, U = any, V = any, W = any, X = any> = any;
export const CLERK_PROVIDER_ID: any = undefined;
export type confirmClientSignedOut<T = any, U = any, V = any, W = any, X = any> = any;
export const confirmClientSignedOut: any = undefined;
export type logoutCleanup<T = any, U = any, V = any, W = any, X = any> = any;
export const logoutCleanup: any = undefined;
export type ProviderAdminAdapter<T = any, U = any, V = any, W = any, X = any> = any;
export const ProviderAdminAdapter: any = undefined;
export type ProviderAdminStatusResult<T = any, U = any, V = any, W = any, X = any> = any;
export const ProviderAdminStatusResult: any = undefined;
export type ProviderSession<T = any, U = any, V = any, W = any, X = any> = any;
export const ProviderSession: any = undefined;
export type ProviderStatusContext<T = any, U = any, V = any, W = any, X = any> = any;
export const ProviderStatusContext: any = undefined;
export type ProviderTokenBroker<T = any, U = any, V = any, W = any, X = any> = any;
export const ProviderTokenBroker: any = undefined;
export type ProviderTokenRequest<T = any, U = any, V = any, W = any, X = any> = any;
export const ProviderTokenRequest: any = undefined;
export type registerAuthProvider<T = any, U = any, V = any, W = any, X = any> = any;
export const registerAuthProvider: any = undefined;
export type registerAuthTokenBroker<T = any, U = any, V = any, W = any, X = any> = any;
export const registerAuthTokenBroker: any = undefined;
export type registerClientAuthStatusResolver<T = any, U = any, V = any, W = any, X = any> = any;
export const registerClientAuthStatusResolver: any = undefined;
export type registerClientSessionRecovery<T = any, U = any, V = any, W = any, X = any> = any;
export const registerClientSessionRecovery: any = undefined;
export type registerProviderAdminAdapter<T = any, U = any, V = any, W = any, X = any> = any;
export const registerProviderAdminAdapter: any = undefined;
export type registerProviderTokenBroker<T = any, U = any, V = any, W = any, X = any> = any;
export const registerProviderTokenBroker: any = undefined;
export type useSessionContext<T = any, U = any, V = any, W = any, X = any> = any;
export const useSessionContext: any = undefined;
